git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  theme:
    selectedLineBgColor:
    - underline
    selectedRangeBgColor:
    - underline
  branchColorPatterns:
    '^upgrade': '#11aaff'

